-- Dữ liệu học phần cho Trường Đại học Sư Phạm Kỹ thuật - Đại học Đà Nẵng
-- Bảng HOCPHAN

INSERT INTO HOCPHAN (MaHocPhan, TenHocPhan, SoTinChi, MaKhoa) VALUES
-- Khoa CNTT
('CNTT001', 'Nhập môn Công nghệ thông tin', 2, 'CNTT'),
('CNTT002', 'Lập trình cơ bản', 3, 'CNTT'),
('CNTT003', 'Cấu trúc dữ liệu và giải thuật', 3, 'CNTT'),
('CNTT004', 'Cơ sở dữ liệu', 3, 'CNTT'),
('CNTT005', 'Lập trình hướng đối tượng', 3, 'CNTT'),
('CNTT006', 'Mạng máy tính', 3, 'CNTT'),
('CNTT007', 'Hệ điều hành', 3, 'CNTT'),
('CNTT008', 'Phát triển ứng dụng Web', 3, 'CNTT'),
('CNTT009', 'Phát triển ứng dụng di động', 3, 'CNTT'),
('CNTT010', 'Trí tuệ nhân tạo', 3, 'CNTT'),
('CNTT011', 'Bảo mật thông tin', 3, 'CNTT'),
('CNTT012', 'Đồ án tốt nghiệp', 10, 'CNTT'),

-- Khoa Điện tử - Viễn thông
('DT001', 'Nhập môn Điện tử - Viễn thông', 2, 'DT'),
('DT002', 'Mạch điện tử', 3, 'DT'),
('DT003', 'Kỹ thuật số', 3, 'DT'),
('DT004', 'Vi xử lý', 3, 'DT'),
('DT005', 'Truyền dữ liệu', 3, 'DT'),
('DT006', 'Mạng viễn thông', 3, 'DT'),
('DT007', 'Thông tin di động', 3, 'DT'),
('DT008', 'Anten và truyền sóng', 3, 'DT'),
('DT009', 'Xử lý tín hiệu số', 3, 'DT'),
('DT010', 'Viễn thông quang', 3, 'DT'),
('DT011', 'Hệ thống thông tin vệ tinh', 3, 'DT'),
('DT012', 'Đồ án tốt nghiệp', 10, 'DT'),

-- Khoa Cơ khí
('CK001', 'Nhập môn Cơ khí', 2, 'CK'),
('CK002', 'Vẽ kỹ thuật', 2, 'CK'),
('CK003', 'Cơ học kỹ thuật', 3, 'CK'),
('CK004', 'Sức bền vật liệu', 3, 'CK'),
('CK005', 'Chi tiết máy', 3, 'CK'),
('CK006', 'Công nghệ chế tạo máy', 3, 'CK'),
('CK007', 'Thiết kế máy', 3, 'CK'),
('CK008', 'Điều khiển tự động', 3, 'CK'),
('CK009', 'Robot công nghiệp', 3, 'CK'),
('CK010', 'Cơ điện tử', 3, 'CK'),
('CK011', 'CAD/CAM', 3, 'CK'),
('CK012', 'Đồ án tốt nghiệp', 10, 'CK'),

-- Khoa Xây dựng
('XD001', 'Nhập môn Xây dựng', 2, 'XD'),
('XD002', 'Vẽ kỹ thuật xây dựng', 2, 'XD'),
('XD003', 'Cơ học kết cấu', 3, 'XD'),
('XD004', 'Sức bền vật liệu xây dựng', 3, 'XD'),
('XD005', 'Kết cấu bê tông cốt thép', 3, 'XD'),
('XD006', 'Kết cấu thép', 3, 'XD'),
('XD007', 'Nền móng', 3, 'XD'),
('XD008', 'Thiết kế đường', 3, 'XD'),
('XD009', 'Thiết kế cầu', 3, 'XD'),
('XD010', 'Quản lý dự án xây dựng', 3, 'XD'),
('XD011', 'Kinh tế xây dựng', 3, 'XD'),
('XD012', 'Đồ án tốt nghiệp', 10, 'XD'),

-- Khoa Kinh tế
('KT001', 'Nhập môn Kinh tế học', 2, 'KT'),
('KT002', 'Kinh tế vi mô', 3, 'KT'),
('KT003', 'Kinh tế vĩ mô', 3, 'KT'),
('KT004', 'Nguyên lý kế toán', 3, 'KT'),
('KT005', 'Tài chính doanh nghiệp', 3, 'KT'),
('KT006', 'Marketing căn bản', 3, 'KT'),
('KT007', 'Quản trị học', 3, 'KT'),
('KT008', 'Thống kê kinh tế', 3, 'KT'),
('KT009', 'Luật kinh tế', 3, 'KT'),
('KT010', 'Quản trị nhân lực', 3, 'KT'),
('KT011', 'Thương mại điện tử', 3, 'KT'),
('KT012', 'Đồ án tốt nghiệp', 10, 'KT'),

-- Khoa Ngoại ngữ
('NN001', 'Tiếng Anh cơ bản 1', 2, 'NN'),
('NN002', 'Tiếng Anh cơ bản 2', 2, 'NN'),
('NN003', 'Tiếng Anh cơ bản 3', 2, 'NN'),
('NN004', 'Tiếng Anh cơ bản 4', 2, 'NN'),
('NN005', 'Ngữ pháp tiếng Anh', 3, 'NN'),
('NN006', 'Từ vựng tiếng Anh', 3, 'NN'),
('NN007', 'Kỹ năng nghe - nói', 3, 'NN'),
('NN008', 'Kỹ năng đọc - viết', 3, 'NN'),
('NN009', 'Văn hóa Anh - Mỹ', 3, 'NN'),
('NN010', 'Dịch thuật', 3, 'NN'),
('NN011', 'Phương pháp giảng dạy', 3, 'NN'),
('NN012', 'Đồ án tốt nghiệp', 10, 'NN'),

-- Khoa Sư phạm
('SP001', 'Tâm lý học đại cương', 2, 'SP'),
('SP002', 'Giáo dục học đại cương', 2, 'SP'),
('SP003', 'Tâm lý học lứa tuổi', 3, 'SP'),
('SP004', 'Tâm lý học sư phạm', 3, 'SP'),
('SP005', 'Lý luận dạy học', 3, 'SP'),
('SP006', 'Phương pháp dạy học', 3, 'SP'),
('SP007', 'Đánh giá trong giáo dục', 3, 'SP'),
('SP008', 'Quản lý giáo dục', 3, 'SP'),
('SP009', 'Công nghệ giáo dục', 3, 'SP'),
('SP010', 'Thực hành sư phạm', 3, 'SP'),
('SP011', 'Rèn luyện nghiệp vụ sư phạm', 3, 'SP'),
('SP012', 'Đồ án tốt nghiệp', 10, 'SP'),

-- Khoa Môi trường
('MT001', 'Nhập môn Khoa học môi trường', 2, 'MT'),
('MT002', 'Hóa học môi trường', 3, 'MT'),
('MT003', 'Sinh học môi trường', 3, 'MT'),
('MT004', 'Vật lý môi trường', 3, 'MT'),
('MT005', 'Quản lý chất thải rắn', 3, 'MT'),
('MT006', 'Xử lý nước thải', 3, 'MT'),
('MT007', 'Xử lý khí thải', 3, 'MT'),
('MT008', 'Đánh giá tác động môi trường', 3, 'MT'),
('MT009', 'Quản lý môi trường', 3, 'MT'),
('MT010', 'Công nghệ xanh', 3, 'MT'),
('MT011', 'Biến đổi khí hậu', 3, 'MT'),
('MT012', 'Đồ án tốt nghiệp', 10, 'MT'),

-- Khoa Vật lý
('VL001', 'Vật lý đại cương 1', 3, 'VL'),
('VL002', 'Vật lý đại cương 2', 3, 'VL'),
('VL003', 'Vật lý đại cương 3', 3, 'VL'),
('VL004', 'Cơ học lượng tử', 3, 'VL'),
('VL005', 'Điện động lực học', 3, 'VL'),
('VL006', 'Vật lý thống kê', 3, 'VL'),
('VL007', 'Vật lý chất rắn', 3, 'VL'),
('VL008', 'Vật lý hạt nhân', 3, 'VL'),
('VL009', 'Vật lý plasma', 3, 'VL'),
('VL010', 'Vật lý thiên văn', 3, 'VL'),
('VL011', 'Phương pháp thực nghiệm', 3, 'VL'),
('VL012', 'Đồ án tốt nghiệp', 10, 'VL'),

-- Khoa Hóa học
('HH001', 'Hóa học đại cương 1', 3, 'HH'),
('HH002', 'Hóa học đại cương 2', 3, 'HH'),
('HH003', 'Hóa học vô cơ', 3, 'HH'),
('HH004', 'Hóa học hữu cơ', 3, 'HH'),
('HH005', 'Hóa học phân tích', 3, 'HH'),
('HH006', 'Hóa lý', 3, 'HH'),
('HH007', 'Hóa sinh', 3, 'HH'),
('HH008', 'Hóa học polymer', 3, 'HH'),
('HH009', 'Hóa học môi trường', 3, 'HH'),
('HH010', 'Hóa học dược phẩm', 3, 'HH'),
('HH011', 'Phương pháp thực nghiệm', 3, 'HH'),
('HH012', 'Đồ án tốt nghiệp', 10, 'HH'),

-- Khoa Toán - Tin học
('TO001', 'Giải tích 1', 3, 'TO'),
('TO002', 'Giải tích 2', 3, 'TO'),
('TO003', 'Đại số tuyến tính', 3, 'TO'),
('TO004', 'Xác suất thống kê', 3, 'TO'),
('TO005', 'Phương trình vi phân', 3, 'TO'),
('TO006', 'Lý thuyết số', 3, 'TO'),
('TO007', 'Tối ưu hóa', 3, 'TO'),
('TO008', 'Lập trình cơ bản', 3, 'TO'),
('TO009', 'Cơ sở dữ liệu', 3, 'TO'),
('TO010', 'Thuật toán và cấu trúc dữ liệu', 3, 'TO'),
('TO011', 'Trí tuệ nhân tạo', 3, 'TO'),
('TO012', 'Đồ án tốt nghiệp', 10, 'TO'),

-- Khoa Sinh học
('SH001', 'Sinh học đại cương', 3, 'SH'),
('SH002', 'Sinh học tế bào', 3, 'SH'),
('SH003', 'Di truyền học', 3, 'SH'),
('SH004', 'Sinh học phân tử', 3, 'SH'),
('SH005', 'Vi sinh vật học', 3, 'SH'),
('SH006', 'Sinh thái học', 3, 'SH'),
('SH007', 'Sinh học phát triển', 3, 'SH'),
('SH008', 'Sinh học tiến hóa', 3, 'SH'),
('SH009', 'Sinh học bảo tồn', 3, 'SH'),
('SH010', 'Công nghệ sinh học', 3, 'SH'),
('SH011', 'Phương pháp thực nghiệm', 3, 'SH'),
('SH012', 'Đồ án tốt nghiệp', 10, 'SH'); 